### ISSUE TITLE
全屏只能在主显示器上，不支持扩展显示器上全屏

### ISSUE THREAD

**Issue by VimIcewind** [movsb/gvim_fullscreen#2]

**Comment by movsb** [comment]
不好意思现在没有Windows系统，问一下，在扩展显示器上尝试全屏会有什么反应呢？

**Comment by VimIcewind** [comment]
现在两个显示器全屏的话，会自动跑到主显示器全屏，没法在扩展显示器全屏

**Comment by VimIcewind** [comment]
我自己改了一下您的代码，然后由于我的显示器在公司，家里没有显示器所以没法测试
            // SetWindowPos(hWnd, HWND_TOP, 0, 0, GetSystemMetrics(SM_CXSCREEN), GetSystemMetrics(SM_CYSCREEN), SWP_FRAMECHANGED);
            SetWindowPos(hWnd, HWND_TOP, GetSystemMetrics(SM_XVIRTUALSCREEN), GetSystemMetrics(SM_YVIRTUALSCREEN), GetSystemMetrics(SM_CXVIRTUALSCREEN), GetSystemMetrics(SM_CYVIRTUALSCREEN), SWP_FRAMECHANGED);
等我周一测试一下试试，再告诉您修改的好不好使。

**Comment by movsb** [comment]
`SM_XVIRTUALSCREEN` 似乎是比较新的参数？不知道老一点的系统支持与否。

显示器的话，我记得是可以通过[`EnumDisplayMonitors`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-enumdisplaymonitors)来拿到的。

> 现在两个显示器全屏的话，会自动跑到主显示器全屏，没法在扩展显示器全屏

你说的这个现象我觉得有点奇怪，虽然不清楚原因。我的代码只是改变了Vim窗口的大小，不应该出现此种现象。

**Comment by VimIcewind** [comment]
SetWindowPos(hWnd, HWND_TOP, 0, 0, GetSystemMetrics(SM_CXSCREEN), GetSystemMetrics(SM_CYSCREEN), SWP_FRAMECHANGED);

**Comment by VimIcewind** [comment]
已经修复并提交Pull request了
