### ISSUE TITLE
set guioptions-=TrLm未生效

### ISSUE THREAD

**Issue by Whernog** [movsb/gvim_fullscreen#5]
set guioptions-=TrLm未生效，菜单栏和工具栏还在，但是写成
set guioptions-=T
set guioptions-=m
set guioptions-=r
这样的分开的形式就生效了，奇怪

**Comment by movsb** [comment]
我查了一下 vim [官方文档](https://vimhelp.org/options.txt.html#add-option-flags)，似乎确实不应该一次性变更多个选项。一直以来居然没发现。😅

> Note that you should add or remove one flag at a time.  If 'guioptions' has
> the value "ab", using "set guioptions-=ba" won't work, because the string "ba"
> doesn't appear.

感觉文档这个说法怪怪的，明明都是[单字符选项](https://vimhelp.org/options.txt.html#%27guioptions%27)，为什么要整体判断呢，单个单个选项判断不就好了吗？😌

感谢提出哦，我改一下。

**Comment by Whernog** [comment]
😁😁😁
