### ISSUE TITLE
调用库函数失败

### ISSUE THREAD

**Issue by IC-killer** [movsb/gvim_fullscreen#7]
win10 gvim8.2.3423 x64
请问该怎么排查问题呢？不知道怎么调试

**Comment by movsb** [comment]
能留下个报错提示吗，我这边现在不方便重现。

**Comment by sqliuchang** [comment]
> 能留下个报错提示或截图吗，我这边现在不方便重现。

vs2022编译的，按下F11之后也是这个错误，vim是[9.0.1528](https://github.com/vim/vim-win32-installer)
![](https://i.imgur.com/xwij9yx.png)

**Comment by movsb** [comment]
@sqliuchang 感觉可能是没有静态编译的原因，我看能不能找个环境试试。可能的话，放个二进制上来。

**Comment by sqliuchang** [comment]
> @sqliuchang 感觉可能是没有静态编译的原因，我看能不能找个环境试试。可能的话，放个二进制上来。

感谢！

**Comment by movsb** [comment]
@sqliuchang  我试了一下，是因为你使用的是 64bit 版本的 Vim，编译成 64bit DLL 就行了（进入 64bit Command Prompt），我先上传一个临时的给你试一下。晚点我继续抽空把自动编译脚本上传上来。（安装了 Windows 虚拟机+vs2022 真不容易。。。）
[gvim_fullscreen.dll.zip](https://github.com/movsb/gvim_fullscreen/files/11914985/gvim_fullscreen.dll.zip)

**Comment by sqliuchang** [comment]
@movsb 非常感谢，可以正常使用

**Comment by movsb** [comment]
Fixed: <https://github.com/movsb/gvim_fullscreen/releases>
